Repository fujaba/fulibFx, pull requests merged in 2025-05, with the labels that each got.

#127 Update Gradle and dependencies
  .github/workflows/gradle-dependencies.yaml
  README.md
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  ludo/build.gradle
  ludo/src/test/java/de/uniks/ludo/AppTest.java
  ludo/src/test/java/de/uniks/ludo/ControllerTest.java
  ludo/src/test/java/de/uniks/ludo/controller/GameOverControllerTest.java
  ludo/src/test/java/de/uniks/ludo/controller/IngameControllerTest.java
  ludo/src/test/java/de/uniks/ludo/controller/SetupControllerTest.java
Labels: dependencies

#129 New error message format
  README.md
  framework/src/main/java/org/fulib/fx/util/FrameworkUtil.java
  ludo/src/main/java/de/uniks/ludo/App.java
  ludo/src/test/java/de/uniks/ludo/AppTest.java
Labels: documentation, enhancement

#130 CI: Dependabot version updates
  .github/dependabot.yml
Labels: enhancement
